//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardsDBSvc
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardsTable", Namespace="http://tempuri.org/")]
    public partial class CardsTable : object
    {
        
        private string cardIdField;
        
        private string cardNameField;
        
        private string cmcField;
        
        private string typeField;
        
        private string subTypesField;
        
        private System.Nullable<int> powerValueField;
        
        private System.Nullable<int> toughnessField;
        
        private string rarityField;
        
        private string cardTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cardId
        {
            get
            {
                return this.cardIdField;
            }
            set
            {
                this.cardIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cardName
        {
            get
            {
                return this.cardNameField;
            }
            set
            {
                this.cardNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cmc
        {
            get
            {
                return this.cmcField;
            }
            set
            {
                this.cmcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string subTypes
        {
            get
            {
                return this.subTypesField;
            }
            set
            {
                this.subTypesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> powerValue
        {
            get
            {
                return this.powerValueField;
            }
            set
            {
                this.powerValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> toughness
        {
            get
            {
                return this.toughnessField;
            }
            set
            {
                this.toughnessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string rarity
        {
            get
            {
                return this.rarityField;
            }
            set
            {
                this.rarityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string cardText
        {
            get
            {
                return this.cardTextField;
            }
            set
            {
                this.cardTextField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CardsDBSvc.SOAPTestSoap")]
    public interface SOAPTestSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<CardsDBSvc.HelloWorldResponse> HelloWorldAsync(CardsDBSvc.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCardToDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<CardsDBSvc.AddCardToDatabaseResponse> AddCardToDatabaseAsync(CardsDBSvc.AddCardToDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCard", ReplyAction="*")]
        System.Threading.Tasks.Task<CardsDBSvc.FindCardResponse> FindCardAsync(CardsDBSvc.FindCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCard", ReplyAction="*")]
        System.Threading.Tasks.Task<CardsDBSvc.DeleteCardResponse> DeleteCardAsync(CardsDBSvc.DeleteCardRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public CardsDBSvc.HelloWorldRequestBody Body;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(CardsDBSvc.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {
        
        public HelloWorldRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public CardsDBSvc.HelloWorldResponseBody Body;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(CardsDBSvc.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody()
        {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCardToDatabaseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCardToDatabase", Namespace="http://tempuri.org/", Order=0)]
        public CardsDBSvc.AddCardToDatabaseRequestBody Body;
        
        public AddCardToDatabaseRequest()
        {
        }
        
        public AddCardToDatabaseRequest(CardsDBSvc.AddCardToDatabaseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCardToDatabaseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cardId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cardName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cmc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string subTypes;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int power;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int toughness;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string cardText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string rarity;
        
        public AddCardToDatabaseRequestBody()
        {
        }
        
        public AddCardToDatabaseRequestBody(string cardId, string cardName, string cmc, string type, string subTypes, int power, int toughness, string cardText, string rarity)
        {
            this.cardId = cardId;
            this.cardName = cardName;
            this.cmc = cmc;
            this.type = type;
            this.subTypes = subTypes;
            this.power = power;
            this.toughness = toughness;
            this.cardText = cardText;
            this.rarity = rarity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCardToDatabaseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCardToDatabaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public CardsDBSvc.AddCardToDatabaseResponseBody Body;
        
        public AddCardToDatabaseResponse()
        {
        }
        
        public AddCardToDatabaseResponse(CardsDBSvc.AddCardToDatabaseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCardToDatabaseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddCardToDatabaseResult;
        
        public AddCardToDatabaseResponseBody()
        {
        }
        
        public AddCardToDatabaseResponseBody(bool AddCardToDatabaseResult)
        {
            this.AddCardToDatabaseResult = AddCardToDatabaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindCardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindCard", Namespace="http://tempuri.org/", Order=0)]
        public CardsDBSvc.FindCardRequestBody Body;
        
        public FindCardRequest()
        {
        }
        
        public FindCardRequest(CardsDBSvc.FindCardRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindCardRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cardId;
        
        public FindCardRequestBody()
        {
        }
        
        public FindCardRequestBody(string cardId)
        {
            this.cardId = cardId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindCardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindCardResponse", Namespace="http://tempuri.org/", Order=0)]
        public CardsDBSvc.FindCardResponseBody Body;
        
        public FindCardResponse()
        {
        }
        
        public FindCardResponse(CardsDBSvc.FindCardResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindCardResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CardsDBSvc.CardsTable FindCardResult;
        
        public FindCardResponseBody()
        {
        }
        
        public FindCardResponseBody(CardsDBSvc.CardsTable FindCardResult)
        {
            this.FindCardResult = FindCardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCard", Namespace="http://tempuri.org/", Order=0)]
        public CardsDBSvc.DeleteCardRequestBody Body;
        
        public DeleteCardRequest()
        {
        }
        
        public DeleteCardRequest(CardsDBSvc.DeleteCardRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteCardRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cardId;
        
        public DeleteCardRequestBody()
        {
        }
        
        public DeleteCardRequestBody(string cardId)
        {
            this.cardId = cardId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCardResponse", Namespace="http://tempuri.org/", Order=0)]
        public CardsDBSvc.DeleteCardResponseBody Body;
        
        public DeleteCardResponse()
        {
        }
        
        public DeleteCardResponse(CardsDBSvc.DeleteCardResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteCardResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteCardResult;
        
        public DeleteCardResponseBody()
        {
        }
        
        public DeleteCardResponseBody(bool DeleteCardResult)
        {
            this.DeleteCardResult = DeleteCardResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface SOAPTestSoapChannel : CardsDBSvc.SOAPTestSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class SOAPTestSoapClient : System.ServiceModel.ClientBase<CardsDBSvc.SOAPTestSoap>, CardsDBSvc.SOAPTestSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SOAPTestSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SOAPTestSoapClient.GetBindingForEndpoint(endpointConfiguration), SOAPTestSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SOAPTestSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SOAPTestSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SOAPTestSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SOAPTestSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SOAPTestSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CardsDBSvc.HelloWorldResponse> CardsDBSvc.SOAPTestSoap.HelloWorldAsync(CardsDBSvc.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<CardsDBSvc.HelloWorldResponse> HelloWorldAsync()
        {
            CardsDBSvc.HelloWorldRequest inValue = new CardsDBSvc.HelloWorldRequest();
            inValue.Body = new CardsDBSvc.HelloWorldRequestBody();
            return ((CardsDBSvc.SOAPTestSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CardsDBSvc.AddCardToDatabaseResponse> CardsDBSvc.SOAPTestSoap.AddCardToDatabaseAsync(CardsDBSvc.AddCardToDatabaseRequest request)
        {
            return base.Channel.AddCardToDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<CardsDBSvc.AddCardToDatabaseResponse> AddCardToDatabaseAsync(string cardId, string cardName, string cmc, string type, string subTypes, int power, int toughness, string cardText, string rarity)
        {
            CardsDBSvc.AddCardToDatabaseRequest inValue = new CardsDBSvc.AddCardToDatabaseRequest();
            inValue.Body = new CardsDBSvc.AddCardToDatabaseRequestBody();
            inValue.Body.cardId = cardId;
            inValue.Body.cardName = cardName;
            inValue.Body.cmc = cmc;
            inValue.Body.type = type;
            inValue.Body.subTypes = subTypes;
            inValue.Body.power = power;
            inValue.Body.toughness = toughness;
            inValue.Body.cardText = cardText;
            inValue.Body.rarity = rarity;
            return ((CardsDBSvc.SOAPTestSoap)(this)).AddCardToDatabaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CardsDBSvc.FindCardResponse> CardsDBSvc.SOAPTestSoap.FindCardAsync(CardsDBSvc.FindCardRequest request)
        {
            return base.Channel.FindCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<CardsDBSvc.FindCardResponse> FindCardAsync(string cardId)
        {
            CardsDBSvc.FindCardRequest inValue = new CardsDBSvc.FindCardRequest();
            inValue.Body = new CardsDBSvc.FindCardRequestBody();
            inValue.Body.cardId = cardId;
            return ((CardsDBSvc.SOAPTestSoap)(this)).FindCardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CardsDBSvc.DeleteCardResponse> CardsDBSvc.SOAPTestSoap.DeleteCardAsync(CardsDBSvc.DeleteCardRequest request)
        {
            return base.Channel.DeleteCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<CardsDBSvc.DeleteCardResponse> DeleteCardAsync(string cardId)
        {
            CardsDBSvc.DeleteCardRequest inValue = new CardsDBSvc.DeleteCardRequest();
            inValue.Body = new CardsDBSvc.DeleteCardRequestBody();
            inValue.Body.cardId = cardId;
            return ((CardsDBSvc.SOAPTestSoap)(this)).DeleteCardAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SOAPTestSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SOAPTestSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SOAPTestSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44368/SOAPTest.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SOAPTestSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44368/SOAPTest.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SOAPTestSoap,
            
            SOAPTestSoap12,
        }
    }
}
